# ChronoPay Configuration File

# The number of seconds a player must be online for before each payout.
payout-interval: 600

# The number of seconds before a payout cycle resets and players who have reached
# the cap and don't have the bypass permission node can start earning again.
# This value is not affected by /cpreload and requires a full reload of the plugin.
payout-cycle-reset-interval: 86400

# The amount of money to give to each player on every payout.
payout-amount: 0.10

# The maximum amount of money a player can earn per-cycle if they don't have the 'chronopay.bypass.cap' permission node.
payout-cap: 5.0

checks:
  address: true
  afk: true
  cap: true

messages:
  payout: ''
  cycle-reset: ''
  cap-reached: ''
  multiple-accounts: ''
  gone-afk: ''