name: 'ChronoPay'
version: '4.0.0'
website: 'https://github.com/syndek/chronopay'
description: 'Reward players for online time.'
author: 'Syndek'

main: 'dev.syndek.chronopay.ChronoPayPlugin'
api-version: '1.16'